sudo: required
services:
  - docker

before_install:
  - docker build -t react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-app"
  env: "ReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-144468571614"
  bucket_path: "react-app"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
